"""empty message

Revision ID: e193c6b0850f
Revises: 4f8718319d1d
Create Date: 2021-09-08 17:49:40.222021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e193c6b0850f'
down_revision = '4f8718319d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('messages', 'ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
